http-port: 23940 #port to run http proxy on
api-port: 23941 #api port
threads: 100 #thread number
source: https://raw.githubusercontent.com/yu-steven/openit/main/utils/pool/pool.yaml
outfile: check.yaml
timeout: 3000 #timeout in miliseconds
