sub:
# - https://clash.ok1991.ml
  - https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
  - https://raw.githubusercontent.com/daycat/freeray/main/optimized.yaml
  - https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/sub/sub_merge_yaml.yml
  - https://gitlab.com/api/v4/projects/35506148/repository/files/data%2Fclash%2Fgeneral.yaml/raw?ref=main&private_token=glpat-JmxhQF1Pta__KamyyKqV
  - https://api.sublink.dev/sub?target=clash&url=https%3A%2F%2Fraw.githubusercontent.com%2Ffreefq%2Ffree%2Fmaster%2Fv2&insert=false&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true # freefq
  - https://api.sublink.dev/sub?target=clash&url=https%3A%2F%2Fraw.githubusercontent.com%2Faiboboxx%2Fv2rayfree%2Fmain%2Fv2&insert=false&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true # v2rayfree
  - https://api.sublink.dev/sub?target=clash&url=https%3A%2F%2Fraw.githubusercontent.com%2FJsnzkpg%2FJsnzkpg%2FJsnzkpg%2FJsnzkpg&insert=false&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true #jsnzkpg
  - https://sub.maoxiongnet.com/sub?target=clash&new_name=true&url=https%3A%2F%2Fraw.githubusercontent.com%2Fyu-steven%2Fopenit%2Fmain%2Futils%2Fpool%2Fpool&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Mini.ini # openit
  - https://proxies.bihai.cf/clash/proxies
  - https://fq.lonxin.net/clash/proxies
  - https://proxy.yugogo.xyz/clash/proxies
  - https://proxypoolss.fly.dev/clash/proxies
  - https://sspool.herokuapp.com/clash/proxies
  - https://free886.herokuapp.com/clash/proxies
# - https://42.194.196.226/clash/proxies
# - http://wxshi.top:9090/clash/proxies
# - http://39.106.12.141:8081/clash/proxies
# - http://49.233.28.108:1314/clash/proxies
