sub: 
# - https://clash.ok1991.ml
  - https://cutt.ly/FProxies_clash #https://t.me/FProxies
  - https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
  - https://raw.githubusercontent.com/daycat/freeray/main/optimized.yaml
  - https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/sub/sub_merge_yaml.yml
  - https://raw.githubusercontent.com/yu-steven/openit/main/utils/pool/pool.yaml #openit回环订阅
  - https://gist.github.com/yu-steven/38dac2b65ef80f208df43388d6c9916f/raw/612d3967f703509290851747eb373978c3332307/mixed.yaml #HTTPS节点Clash格式
  - https://gitlab.com/api/v4/projects/35506148/repository/files/data%2Fclash%2Fgeneral.yaml/raw?ref=main&private_token=glpat-JmxhQF1Pta__KamyyKqV #https://t.me/univstar
  - https://api.sublink.dev/sub?target=clash&url=http://beikui.tk/xhjjd #北葵分享
  - https://api.sublink.dev/sub?target=clash&url=https://raw.githubusercontent.com/freefq/free/master/v2 #freev2
  - https://api.sublink.dev/sub?target=clash&url=https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2 #v2rayfree
  - https://api.sublink.dev/sub?target=clash&url=https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg #jsnzkpg
  - https://proxies.bihai.cf/clash/proxies
  - https://fq.lonxin.net/clash/proxies
  - https://proxy.yugogo.xyz/clash/proxies
  - https://proxypoolss.fly.dev/clash/proxies
  - https://sspool.herokuapp.com/clash/proxies
  - https://free886.herokuapp.com/clash/proxies
  - https://42.194.196.226/clash/proxies
  - http://wxshi.top:9090/clash/proxies
  - http://39.106.12.141:8081/clash/proxies
  - http://49.233.28.108:1314/clash/proxies
