name: Nodes
on: 
  # schedule:
    # - cron: '*/40 * * * *'
  workflow_dispatch:

jobs:
  cl-job: #input./utils/pool/config.yaml
    name: Collecting 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: requirements.txt
      run: pip install -r ./utils/pool/requirements.txt
    - name: main.py
      run: cd ./utils/pool/ && python main.py
    - run: ./.github/update-repo.sh || true   #output./utils/pool/output.yaml

  rm-job: #input./utils/pool/output.yaml
    name: rm
    needs: cc-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: subconverter
      run: ./utils/subconverter/subconverter -g --artifact "rm"   #output./utils/subconverter/rm1
    - name: rm
      run: | #input./utils/subconverter/rm1
         mv ./utils/subconverter/rm1 ./utils/rm/rm1
         cd ./utils/rm/
         base64 -d rm1 > rm2 #output./utils/rm/rm2
         #input./utils/rm/rm2
         npm run start #output./utils/rm/rm3
    - name: output-rm-b64 & output.yaml
      run: | #input./utils/rm/rm3
         rm ./utils/rm/rm1 ./utils/rm/rm2
         base64 ./utils/rm/rm3 > ./utils/pool/output-rm-b64 -w 0 && rm rm3
         ./.github/update-repo.sh || true   #output./utils/pool/output-rm-b64
         sleep 1m
         #input./utils/pool/output-rm-b64
         ./utils/subconverter/subconverter -g --artifact "output"
         mv ./utils/subconverter/output.yaml ./utils/pool/output.yaml
    - run: ./.github/update-repo.sh || true   #output./utils/pool/output.yaml

  cc-job: #input./utils/pool/output.yaml
    name: ClashCheck
    # needs: cl-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: requirements.txt
      run: pip3 install -r ./utils/clashcheck/requirements.txt
    - name: main.py
      run: cd ./utils/clashcheck/ && python3 main.py && python3 main.py && python3 main.py
    - run: ./.github/update-repo.sh || true   #output./utils/clashcheck/check.yaml

  et-job: #input./utils/clashcheck/check.yaml & ./utils/pool/pool & ./utils/pool/output.yaml
    name: Encode & Translate
    needs: rm-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: subconverter
      run: | #input./utils/clashcheck/check.yaml & ./utils/pool/pool & ./utils/pool/output.yaml
         ./utils/subconverter/subconverter -g #output./utils/subconverter/long & ./utils/subconverter/Clash.yaml & ./utils/subconverter/pool.yaml & ./utils/subconverter/rm1 & ./utils/subconverter/output.yaml
         mv ./utils/subconverter/long ./long || true
         mv ./utils/subconverter/Clash.yaml ./Clash.yaml ||true
         rm ./utils/subconverter/pool.yaml ./utils/subconverter/rm1 ./utils/subconverter/output.yaml
         #input./long
         base64 -d ./long | tee url 2 #output./url &./2
         #input./.github/url.sh
         ./.github/url.sh > ./1 #output./1
         #input./1 & ./2
         cat 1 2 > 3 && rm 1 2 #output./3
         #input./3
         base64 3 > https -w 0 && rm 3 #output./https
    - run: ./.github/update-repo.sh || true   #output./long & ./Clash.yaml & ./url & ./https

  long:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/long
  HTTPS:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/https
  Clash:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Clash.yaml
  Quanx:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: sleep 0.01 #curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Quanx.conf
