name: Nodes
on: 
  # schedule:
    # - cron: '*/32 0-14 * * *'
    # - cron: '51 14-23 * * *'
  workflow_dispatch:

jobs:
  cl-job: #input./utils/pool/config.yaml
    name: Collecting 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: requirements.txt
      run: pip install -r ./utils/pool/requirements.txt
    - name: main.py
      run: cd ./utils/pool/ && python main.py
    - run: ./.github/update-repo.sh || true   #output./utils/pool/output.yaml

  cc-job: #input./utils/clashcheck/config.yaml
    name: ClashCheck
    # needs: cl-job
    runs-on: self-hosted #python git pip
    # runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
         pip config set local.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - name: requirements.txt
      run: pip3 install -r ./utils/clashcheck/requirements.txt
    - name: main.py
      run: cd ./utils/clashcheck/ && python3 main.py && python3 main.py && python3 main.py
    - run: ./.github/update-repo.sh || true   #output./utils/clashcheck/check.yaml
    - run: ./.github/update-repo.sh || true   #output./utils/clashcheck/check.yaml;重复步骤以缓解有概率的push失败

  rm-job: #input./utils/clashcheck/check.yaml
    name: rm
    needs: cc-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: subconverter
      run: ./utils/subconverter/subconverter -g --artifact "rm"
    - name: rm
      run: | 
         mv ./utils/subconverter/rm1 ./utils/rm/rm1
         cd ./utils/rm/
         base64 -d rm1 > rm2
         npm install
         npm start
    - name: url & https & check
      run: | 
         rm ./utils/rm/rm1 ./utils/rm/rm2
         mv ./utils/rm/url ./url
         base64 ./url > ./utils/pool/check -w 0 
         ./.github/url.sh > ./1
         cp ./url ./2
         cat 1 2 > 3 && rm 1 2
         base64 3 > https -w 0 && rm 3
    - run: ./.github/update-repo.sh || true   #output./url & ./https & ./utils/pool/check

  et-job: #input./utils/pool/check & ./utils/pool/pool
    name: Encode & Translate
    needs: rm-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: subconverter
      run: | 
         ./utils/subconverter/subconverter -g
         mv ./utils/subconverter/long ./long || true
         mv ./utils/subconverter/Clash.yaml ./Clash.yaml ||true
         rm ./utils/subconverter/pool.yaml ./utils/subconverter/rm1
    - run: ./.github/update-repo.sh || true   #output./long & ./Clash.yaml & ./utils/pool/pool.yaml

  long:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/long
  HTTPS:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/https
  Clash:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Clash.yaml
  Quanx:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: sleep 0.01 #curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Quanx.conf
