name: Nodes
on: 
  schedule:
    - cron: '*/32 0-14 * * *'
    - cron: '*/51 14-23 * * *'
  workflow_dispatch:

jobs:
  cs-job: #input./utils/pool/config.yaml
    name: Collecting & Speedtest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: requirements.txt 1
      run: | 
         pip install -r ./utils/pool/requirements.txt
         pip install -r ./utils/clashcheck/requirements.txt
    - name: pool
      run: cd ./utils/pool/ && python main.py && cd && mv ./utils/pool/output.yaml ./utils/clashcheck/input.yaml
    - name: clashcheck
      run: cd ./utils/clashcheck/ && python main.py && python main.py && python main.py
    - run: ./.github/update-repo.sh || true   #output./utils/pool/output.yaml

  rr-job: #input./utils/clashcheck/check.yaml
    name: Remove & Remark
    needs: cs-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: subconverter #input./utils/clashcheck/check.yaml
      run: ./utils/subconverter/subconverter -g --artifact "rm" #output./utils/subconverter/rm1
    - name: rm
      run: | #input./utils/subconverter/rm1
         mv ./utils/subconverter/rm1 ./utils/rm/rm1
         cd ./utils/rm/
         #input./utils/rm/rm1
         base64 -d rm1 > rm2 #output./utils/rm/rm2
         npm install #input./utils/rm/package-lock.json
         #input./utils/rm/rm2
         npm start #output./utils/rm/url
    - name: url & https & check
      run: | #input./utils/rm/url ./url ./.github/url.sh ./1 ./2 ./3
         rm ./utils/rm/rm1 ./utils/rm/rm2
         #input./utils/rm/url
         mv ./utils/rm/url ./url #output./url
         #input./url
         base64 ./url > ./utils/pool/check -w 0 #output./utils/pool/check
         #input./.github/url.sh
         ./.github/url.sh > ./1 #output./1
         #input./url
         cp ./url ./2 #output./2
         #input./1 ./2
         cat 1 2 > 3 && rm 1 2 #output./3
         #input./3
         base64 3 > https -w 0 && rm 3 #output./https
    - run: ./.github/update-repo.sh || true   #output./url ./https ./utils/pool/check

  et-job: #input./utils/pool/check ./utils/pool/pool
    name: Encode & Translate
    needs: rr-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: subconverter
      run: | #input./utils/pool/check ./utils/pool/pool ./utils/clashcheck/check.yaml
         ./utils/subconverter/subconverter -g 
         #output./utils/subconverter/long ./utils/subconverter/Clash.yaml ./utils/subconverter/pool.yaml ./utils/subconverter/rm1
         mv ./utils/subconverter/long ./long || true
         mv ./utils/subconverter/Clash.yaml ./Clash.yaml || true
         rm ./utils/subconverter/pool.yaml ./utils/subconverter/rm1
    - run: ./.github/update-repo.sh || true   #output./long ./Clash.yaml

  long:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/long
  HTTPS:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/https
  Clash:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Clash.yaml
  Quanx:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: true #curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Quanx.conf
