
name: Nodes
on: 
  schedule:
    - cron: '*/40 * * * *'
  workflow_dispatch:

jobs:
  cl-job:
    name: Collecting 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: requirements.txt
      run: pip install -r ./utils/pool/requirements.txt
    - name: main.py
      run: cd utils/pool/ && python main.py
    - run: ./.github/update-repo.sh

  cc-job:
    name: ClashCheck
    # needs: cl-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: requirements.txt
      run: pip3 install -r ./utils/clashcheck/requirements.txt
    - name: main.py
      run: cd utils/clashcheck/ && python3 main.py && python3 main.py && python3 main.py
    - run: ./.github/update-repo.sh || true

  rm-job:
    name: rm
    needs: cc-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: rm
      run: | 
         ./utils/subconverter/subconverter -g --artifact "rm"
         mv ./utils/subconverter/rm ./rm
         base64 -d rm > url && rm rm
         sed '/^$/d' url
         sed -i '/#.*$/d' url
         sed -i -n 'G; /^\(.*\n\).*\n\1/d; h; P' url
         base64 url > ./utils/subconverter/check -w 0 
    - run: ./.github/update-repo.sh || true

  et-job:
    name: Encode & Translate
    needs: rm-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: git config --local user.email "actions@github.com"&&git config --local user.name "GitHub Actions"
    - name: subconverter
      run: | 
         ./utils/subconverter/subconverter -g
         mv ./utils/subconverter/long ./long || true
         mv ./utils/subconverter/Clash.yaml ./Clash.yaml ||true
         base64 -d long | tee 2 url
         ./.github/url.sh > ./1
         cat 1 2 > 3 && rm 1 2
         base64 3 > https -w 0 && rm 3
    - run: ./.github/update-repo.sh

  long:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/long
  HTTPS:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/https
  Clash:
    needs: et-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Clash.yaml
  Quanx:
   needs: et-job
   runs-on: ubuntu-latest
   steps:
   - name: CDN
     run: sleep 0.01 #curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Quanx.conf
