name: ProxyPool

on:
  schedule:
    - cron: '*/40 * * * *'
  workflow_dispatch:

jobs:
  cl-job:
    name: Collecting 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: git config --local user.email "actions@github.com"&&git config --local user.name "GitHub Actions"
    - name: requirements.txt
      run: pip install -r ./utils/pool/requirements.txt
    - name: main.py
      run: cd utils/pool/ && python main.py
    - run: ./.github/update-repo.sh
