name: Reuse
on: 
  #push:
  #  paths:
  #    - 'url'
  workflow_dispatch:
jobs:
  bf-job:
    name: Reuse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: |
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
    - name: pool
      run: |
         base64 url > pool -w 0
         mv ./pool ./utils/pool/pool
    - run: ./.github/update-repo.sh
